# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    defaults:
        run:
            working-directory: ./client
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy index to 404
        run: cp dist/index.html dist/404.html

      - name: Copy other pages that shouldn't return a 404 (GitHub Pages limitation)
        run: mkdir dist/legendaries && cp dist/index.html dist/legendaries/index.html && mkdir dist/stats && cp dist/index.html dist/stats/index.html && mkdir dist/reapers && cp dist/index.html dist/reapers/index.html && mkdir dist/build && cp dist/index.html dist/build/index.html
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: client/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
